<?php
/** @var $message \App\Model\Eloquent\Message */
/** @var $user \App\Model\User */
$user = $this->user;
/** @var Illuminate\Database\Eloquent\Collection $messages */
$messages = $this->messages;
?>

<?php if(!$messages->isEmpty()): ?>
    <?php foreach ($messages as $message): ?>
        <div class="message">
            <? if($user->isAdmin()): ?>
                <div class="admin">
                    <a href="/admin/deleteMessage/?id=<?=$message->id;?>">delete #<?=$message->id;?></a>
                </div>
            <? endif; ?>
            <span class="date"><?=$message->created_at;?> </span>
            <? if($author = $message->author):?>
                <span class="author"><?=htmlspecialchars($author->getName());?></span>
            <? else: ?>
                <span class="author">Сообщение от удаленного пользователя</span>
            <? endif; ?>
            <div class="text"><?=htmlspecialchars(nl2br($message->text));?></div>
            <? if($message->image):?>
                <div><img src="/images/<?=$message->image;?>" style="width: 150px;"></div>
            <? endif;?>
        </div>
    <?php endforeach; ?>

<?php else: ?>
    Сообщений пока нет
<?php endif; ?>
